apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../templates/standard

labels:
- pairs:
    app: jellyfin
  includeSelectors: true

namePrefix: jellyfin-

images:
- name: app
  newName: jellyfin/jellyfin
  newTag: "2026052506"
