values:
  instance:
    cluster:
      networkPolicy: false
    components:
      - source-controller
      - kustomize-controller
      - helm-controller
      - notification-controller
    sync:
      kind: GitRepository
      url: https://github.com/Insert-Generic-Name/homelab
      ref: refs/heads/resourceset-testing #switch me later to refs/heads/main
      path: ./kubernetes/flux/cluster/platform
      interval: 1m
