# Patches for talosconfig
---
apiVersion: v1alpha1
kind: KubeNetworkConfig
podSubnets:
  - 10.42.0.0/16
serviceSubnets:
  - 10.43.0.0/16
---
apiVersion: v1alpha1
kind: KubeFlannelCNIConfig
$patch: delete
---
apiVersion: v1alpha1
kind: KubeProxyConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeNodeConfig
taints:
  node-role.kubernetes.io/control-plane:
    $patch: delete
