services:
  app:
    container_name: doco-cd-updater
    image: ghcr.io/kimdre/doco-cd:latest
    restart: unless-stopped
    environment:
      TZ: Europe/Madrid
      HTTP_PORT: 8000
      POLL_CONFIG: |
        - url: https://github.com/Insert-Generic-Name/homelab.git
          reference: refs/heads/main
          interval: 300
          target: updater
      SCHEDULER_ENABLED: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - updater-data:/data

volumes:
  updater-data:
