#      # Repository-based deployments require .doco-cd.y(a)ml (or .doco-cd.<target>.y(a)ml when target is set).

services:
  app:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:latest
    restart: unless-stopped
    # ports:
    #   # - "80:80" # Webhook endpoint
    #   - "9120:9120" # Prometheus metrics
    # For all available environment variables and explanations, see https://doco.cd/latest/App-Settings/
    environment:
      TZ: Europe/Madrid
      LOG_LEVEL: DEBUG
      POLL_CONFIG: |
        - url: https://github.com/Insert-Generic-Name/homelab.git
          reference: main
          interval: 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  data:
