services:
  openbao:
    image: openbao/openbao:latest
    container_name: openbao
    restart: ${RESTART_POLICY}
    environment:
      - BAO_DEV_ROOT_TOKEN_ID=${TOKEN}
      - BAO_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    # volumes:
    #   - ./bao-config:/openbao/config
    expose:
      - 8200
    networks:
      - bao

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: ${RESTART_POLICY}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_bao_data:/data
      - caddy_bao_config:/config
    networks:
      - bao

volumes:
  caddy_bao_data:
  caddy_bao_config:

networks:
  bao:
