apiVersion: v1
kind: Secret
metadata:
  name: vault-backend-credentials-secret
  namespace: default
stringData:
  credentials.json: |
    ${CF_TOKEN}

How do I approach secrets now? Do I just use the CLI to patch them like onedr0p or use age/sops?