apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
  namespace: forgejo
spec:
  target:
    template:
      engineVersion: v2
      data:
        username: Insert-Generic-Name
        password: "{{ .password }}"
        email: "{{ .email }}"
  data:
    - secretKey: password
      remoteRef:
        key: forgejo
        property: password

    - secretKey: email
      remoteRef:
        key: forgejo
        property: password
