apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin-password
  namespace: forgejo
spec:
  data:
    - secretKey: password
      remoteRef:
        key: forgejo
        property: password
