{{ if eq .Values.Kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.Replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.Image.name }}:{{ .Values.Image.tag }}"
        ports: {{- range .Values.Ports }}
        - name: {{ .name | default "http" }}
          protocol: {{ .protocol | default "TCP" }}
          containerPort: {{ .targetPort | default .port }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        {{- if .Values.volumeMounts }}
        volumeMounts: {{- range .Values.volumeMounts }}
        - name: {{ .name | default "pvc" }}
          mountPath: {{ .mountPath | default "/data"}}
        {{- end }}
        {{- end }}
{{- end }}