apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  {{- if eq .Values.Kind "StatefulSet" }}
  clusterIP: None 
  {{- else }}
  type: {{ .Values.ServiceType | default "ClusterIP" }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}
  ports: {{- range .Values.Ports }}
    - name: {{ .name | default "http" }}
      protocol: {{ .protocol | default "TCP" }}
      port: {{ .port }} 
      targetPort: {{ .targetPort | default .port }}
    {{- end }} 