{{ if eq .Values.appKind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  serviceName: {{ .Values.appName }}
  replicas: {{ .Values.appReplicas | default 1 }}
  minReadySeconds: {{ .Values.appminReadySeconds | default 10 }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.appterminationGracePeriodSeconds | default 60 }}
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.appImage.name }}:{{ .Values.appImage.tag }}"
        ports: {{- range .Values.appPorts }}
        - name: {{ .name | default "http" }}
          protocol: {{ .protocol | default "TCP" }}
          containerPort: {{ .targetPort | default .port }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.appName }}
        volumeMounts: {{- range .Values.appVolumeMounts }}
        - name: {{ .name | default "pvc" }}
          mountPath: {{ .mountPath | default "/data"}}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 5Gi
{{- end }}