{{ if eq .Values.Kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  replicas: {{ .Values.Replicas | default 1 }}
  minReadySeconds: {{ .Values.minReadySeconds | default 10 }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 60 }}
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.Image.name }}:{{ .Values.Image.tag }}"
        ports: {{- range .Values.Ports }}
        - name: {{ .name | default "http" }}
          protocol: {{ .protocol | default "TCP" }}
          containerPort: {{ .targetPort | default .port }}
        {{- end }}
        {{- if .Values.environment }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        {{- end }}
        {{- if .Values.volumeMounts }}
        volumeMounts: {{- range .Values.volumeMounts }}
        - name: {{ .name | default "pvc" }}
          mountPath: {{ .mountPath | default "/data"}} # Remember EmptyDirs for cache
        {{- end }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 5Gi
{{- end }}