apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  chartRef:
    kind: HelmChart
    name: rook-ceph-cluster
  values:
    monitoring:
      enabled: false #changeme
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          replicated:
            size: 1 #changeme to 3
        storageClass:
          reclaimPolicy: Retain
    cephFileSystems:
      - name: ceph-filesystem
        spec:
          metadataPool:
            replicated:
              size: 1 #changeme to 3
          dataPools:
            replicated:
              size: 1 #changeme to 3
        storageClass:
          reclaimPolicy: Retain
    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            replicated:
              size: 1 #change me to 3
        storageClass:
          reclaimPolicy: Retain
          # Enable HTTPRoute
    #   route:
    #   # Enable an ingress for the ceph-objectstore
    #   enabled: false
    #   # The ingress port by default will be the object store's "securePort" (if set), or the gateway "port".
    #   # To override those defaults, set this ingress port to the desired port.
    #   # port: 80
    #   # annotations: {}
    #   # host:
    #   #   name: objectstore.example.com
    #   #   path: /
    #   #   pathType: PathPrefix
    #   # parentRefs:
    #   #   - name: internal
    #   #     namespace: kube-system
    #   #     sectionName: https
    # cephClusterSpec:
    #   mon:
    #     count: 1 #change me to 3
    #   mgr:
    #     count: 1 #change me to 2
# route:
#   # -- Enable an HTTPRoute for the ceph-dashboard
#   dashboard: {}
#     # labels:
#     #   external-dns/private: "true"
#     # annotations:
#     #   external-dns.alpha.kubernetes.io/hostname: dashboard.example.com
#     #   nginx.ingress.kubernetes.io/rewrite-target: /ceph-dashboard/$2
#     # host:
#     #   name: dashboard.example.com
#     #   path: "/"
#     #   pathType: PathPrefix
#     # parentRefs:
#     #   - name: internal
#     #     namespace: kube-system
#     #     sectionName: https
