apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  chartRef:
    kind: HelmChart
    name: rook-ceph-cluster
  values:
    monitoring:
      enabled: false #changeme
    cephClusterSpec:
      mon:
        count: 1 #change me to 3
      mgr:
        count: 1 #change me to 2
