apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 24h
  chart:
    spec:
      chart: ./helm
      version: "1.0.0"
      sourceRef:
        kind: GitRepository
        name: jellyfin
  values:
    Kind: Deployment

    Image:
      name: jellyfin/jellyfin
      tag: unstable

    Ports:
      - name: http
        protocol: TCP
        port: 8096

    # environment:
