apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "cilium-lb-ip-pool"
spec:
  allowFirstLastIPs: "No"
  blocks:
    #    - cidr: "192.168.1.0/24"
    - cidr: "192.168.1.0/24"
    - start: "192.168.1.0"
      stop: "192.168.1.10"
