services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      # API & Dashboard
      - "--api=false"
      # Certificate management
      - "--certificatesresolvers.cf.acme.email=${EMAIL}"
      - "--certificatesresolvers.cf.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.cf.acme.storage=/certs/acme.json"
      - "--certificatesresolvers.cf.acme.profile=shortlived"
      - "--certificatesresolvers.cf.acme.dnsChallenge=true"
      - "--certificatesresolvers.cf.acme.dnschallenge.provider=cloudflare"
      - "--entrypoints.websecure.http.tls.certresolver=cf"
      # Logs
      - "--log.level=DEBUG"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CLOUDFLARE_EMAIL=${EMAIL}
      - CF_DNS_API_TOKEN=${CF_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/certs
    networks:
      - proxy

networks:
  proxy:
    name: proxy

volumes:
  certs:
