name: doco-cd-updater
reference: main
working_dir: ./docker/doco-cd
compose_files:
  - compose.updater.yaml
force_recreate: true
---
name: main
working_dir: ./docker/apps/
auto_discovery:
  enabled: true
  depth: 1
  delete: true
  remove_volumes: true
reconciliation: true
external_secrets:
  DOMAIN: 8c0d8996-a896-4873-933f-b4a500c30c5d
  EMAIL: 43f0364b-b9c3-4dff-8453-b4a500c2f4c7
  CF_TOKEN: cdddf02e-b2bf-4948-ba0e-b4a500c3f539
