apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  data:
    - secretKey: woodpecker-forgejo-client
      remoteRef:
        key: woodpecker
        property: woodpecker-forgejo-client

    - secretKey: woodpecker-forgejo-secret
      remoteRef:
        key: woodpecker
        property: woodpecker-forgejo-secret
