- op: replace
  path: /spec/template/spec/containers/0/volumeMounts
  value: 
    - name: media
      mountPath: /media
    - name: config
      mountPath: /config
    - name: cache
      mountPath: /cache 