services:
  # Main instance
  app:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:latest
    restart: unless-stopped
    environment:
      SECRET_PROVIDER: bitwarden_sm
      SECRET_PROVIDER_API_URL: https://vault.bitwarden.com/api
      SECRET_PROVIDER_IDENTITY_URL: https://vault.bitwarden.com/identity
      SECRET_PROVIDER_ACCESS_TOKEN: ${SECRET_PROVIDER_ACCESS_TOKEN:?error}

      APPRISE_API_URL: "http://apprise:8000/notify"
      APPRISE_NOTIFY_URLS: ${APPRISE_NOTIFY_URLS}
      APPRISE_NOTIFY_LEVEL: info
      TZ: ${TZ}
      LOG_LEVEL: INFO
      HTTP_PORT: 80
      DEPLOY_CONFIG_BASE_DIR: ./docker/
      MAX_CONCURRENT_DEPLOYMENTS: 10
      POLL_CONFIG: |
        - url: https://github.com/Insert-Generic-Name/homelab.git
          reference: main
          interval: 10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - doco-cd

networks:
  doco-cd:
    name: doco-cd

volumes:
  data:
