apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: flux-instance
  namespace: flux-system

spec:
  interval: 5m
  targetNamespace: flux-system
  sourceRef:
    kind: OCIRepository
    name: flux-instance
  path: "./kubernetes/apps/flux-system/flux-instance/app"
  prune: false
