apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: platform-rs
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "5m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: flux-operator
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: platform-inputs

  resources:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: << inputs.charts.name >>
        namespace: flux-system
      spec:
        dependsOn:
          - name: << inputs.charts.dependsOn >>
        wait: true
        interval: 5m
        prune: << inputs.charts.prune | default true >>
        deletionPolicy: WaitForTermination
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        path: ./kubernetes/deployment/platform/<< inputs.charts.namespace >>/<< inputs.charts.name >>
        targetNamespace: << inputs.charts.namespace >>
        postBuild:
          substituteFrom:
            - kind: Secret
              name: domain

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: << inputs.charts.name >>
        namespace: flux-system

      spec:
        interval: 5m
        chartRef:
          kind: OCIRepository
          name: << inputs.charts.name >>
        valuesFrom:
          - kind: ConfigMap
            name: << inputs.charts.name >>
        driftDetection:
          mode: enabled
        install:
          crds: CreateReplace
        upgrade:
          crds: CreateReplace
          cleanupOnFail: true
          strategy:
            name: RemediateOnFailure
        rollback:
          cleanupOnFail: true

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: << inputs.charts.name >>
        namespace: flux-system
      spec:
        interval: 5m
        url: << inputs.charts.source.url >>
        ref:
          tag: << inputs.charts.source.tag >>
        layerSelector:
          mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
          operation: copy
