services:
  openbao:
    image: openbao/openbao:2.6.1
    container_name: openbao
    restart: unless-stopped
    command: server
    expose:
      - "8200"
    #environment:
    volumes:
      - ./config.hcl:/openbao/config/config.hcl
      - /openbao/data:/openbao/raft
      - /openbao/logs:/openbao/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bao.rule=Host(`openbao.external.${DOMAIN}`)"
      - "traefik.http.routers.bao.entrypoints=websecure"
      - "traefik.http.routers.bao.tls=true"
      - "traefik.http.routers.bao.tls.certresolver=cf"
      - "traefik.http.services.bao.loadbalancer.server.port=8200"
    networks:
      - proxy

networks:
  proxy:
