apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
spec:
  chartRef:
    kind: OCIRepository
    name: coredns
  interval: 5m
  values:
    replicaCount: 1 # change me to 2 later
    # prometheus: enable me later!
    serviceAccount:
      create: true
