apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ./default
  # - ./download
  - ./envoy-gateway-system
  - ./flux-system
  #- ./infra
  - ./kube-system
  - ./media
  # - ./observability
  # - ./productivity
  #- ./security
  #- ./storage
