services:
  openbao:
    image: openbao/openbao:2.6.1
    container_name: openbao
    restart: unless-stopped
    command: server
    expose:
      - "8200"
    #environment:
    volumes:
      - ./config.hcl:/openbao/config/config.hcl
      - /openbao/data:/openbao/raft
      - /openbao/logs:/openbao/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bao-external.rule=Host(`openbao.external.${DOMAIN:?error}`)"
      - "traefik.http.routers.bao-external.entrypoints=websecure"
      - "traefik.http.routers.bao-external.tls=true"
      - "traefik.http.routers.bao-external.tls.certresolver=cf"
      - "traefik.http.services.bao-external.loadbalancer.server.port=8200"

      - "traefik.http.routers.bao-internal.rule=Host(`openbao.home.arpa`)"
      - "traefik.http.routers.bao-internal.entrypoints=websecure"
      - "traefik.http.routers.bao-internal.tls=true"
      - "traefik.http.services.bao-internal.loadbalancer.server.port=8200"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
