# Kind: Deployment or StatefulSet
#
# Image:
#   name: docker/image
#   tag: latest
#
# Ports:
#   - name: http
#     protocol: TCP
#     port: 80
#   - name: dns
#     protocol: UDP
#     port: 53
#
# environment:
#   DevopsIsPain: true
#   CodingStatus: "Desperation"
#   EncryptedWithBase64: "GotFired"
#
# volumeMounts:
#   - name: TrustMeBro
#     mountPath: /dev/null
