when:
  - event: push
    branch: main
  - event: manual

steps:
  # Invoke flux operator CLI via entrypoint instead of command since the container lacks a shell
  - name: Build fluxcd manifests
    image: ghcr.io/controlplaneio-fluxcd/flux-operator-cli:v0.57.0
    entrypoint:
      [
        "flux-operator",
        "build",
        "rset",
        "-f",
        "./kubernetes/flux-system/cluster/platform/rs.yaml",
      ]
  - name: Validate generated manifests
    image: ghcr.io/controlplaneio-fluxcd/flux-operator-cli:v0.57.0
    entrypoint:
      [
        "flux-operator",
        "build",
        "rset",
        "-f",
        "./kubernetes/flux-system/cluster/platform/rs.yaml",
      ]
  - name: fail script on purpose ( testing)
    image: debian:latest
    commands:
      - yamllint .
    # backend_options:
    #   kubernetes:
    #     securityContext:
    #       runAsUser: 1000
    #       runAsGroup: 1000
    #       allowPrivilegeEscalation: false
    #       # seccompProfile:
    #       #   type: RuntimeDefault
    #       capabilities:
    #         drop:
    #           - ALL

  - name: a-test-step
    image: alpine
    commands:
      - echo "Testing ..."
