when:
  - event: push
    branch: main

steps:
  - name: Build fluxcd manifests and validate them
    image: debian #ghcr.io/controlplaneio-fluxcd/flux-operator-cli:v0.57.0
    commands:
      - flux-operator build rset --file ../kubernetes/flux-system/cluster/platform/rs.yaml
      - yamllint .
    backend_options:
      kubernetes:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          # seccompProfile:
          #   type: RuntimeDefault
          capabilities:
            drop:
              - ALL

  - name: a-test-step
    image: alpine
    commands:
      - echo "Testing ..."
      - cat some-file.txt
